### ISSUE TITLE
Using rest client to call the /build api failed

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd-example#1]
Looks like "sn-cicd" didn't pick up any values from the post request. the call return with "200" on client side, but server console show errors.
```
curl -X POST -i http://localhost:8080/build --data '{
    "requestor": {
        "userName": "testuser",
        "fullName": "testuser",
        "email": "testuser@mail.com"
    },
   ...........
}'
```

Got error on sn-cicd server console
```
start CI/CD
{ build:
   { requestor: { userName: null, fullName: null, email: null } },
  atf:
   { credentials: { name: null, oauth: { accessToken: null } } },
  updateSet: null,
  application:
   { id: null,
     name: null,
     organization: 'company',
     git: { repository: null, remoteUrl: null } },
  host:
   { name: null, credentials: { oauth: { accessToken: null } } } }
>>> buildUpdateSetOnBranch
addStep, no run instance found. State: setUpdateSet-error
Unhandled rejection TypeError: Cannot read property 'sys_id' of null
    at Object.CICD.build.setProgress (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/sn-cicd/lib/cicd.js:765:44)
    at Promise.try (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/sn-cicd/lib/cicd.js:1160:35)
    at tryCatcher (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/method.js:39:29)
    at Promise.try.then.then.then.then.catch (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/sn-cicd/lib/cicd.js:1159:31)
    at tryCatcher (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/brianchen/nbn-wk/sn-cicd-example/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
```

tracing the sn-cicd lib, the cicd.js, got the `req.body` is empty

**Comment by gitlabbin** [comment]
need add `Content-Type`, close it
