### ISSUE TITLE
Browser the link "http://localhost:8080/us.html", server got error

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd-example#2]
Click the link "Update-Sets"  http://localhost:8080/us.html

Server console show error:
```
Unhandled rejection TypeError: Cannot read property 'host' of undefined
    at result.map (/Users/brianchen/wk/sn-cicd-example/node_modules/sn-cicd/lib/cicd.js:2210:34)
    at Array.map (<anonymous>)
    at db.us.find.then (/Users/brianchen/wk/sn-cicd-example/node_modules/sn-cicd/lib/cicd.js:2209:33)
    at tryCatcher (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/brianchen/wk/sn-cicd-example/node_modules/bluebird/js/release/nodeback.js:42:21
    at newArguments.(anonymous function) (/Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/cursor.js:126:19)
    at /Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/cursor.js:193:12
    at /Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/Users/brianchen/wk/sn-cicd-example/node_modules/async/lib/async.js:130:20)
    at /Users/brianchen/wk/sn-cicd-example/node_modules/nedb/lib/datastore.js:323:11
    at fn (/Users/brianchen/wk/sn-cicd-example/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/Users/brianchen/wk/sn-cicd-example/node_modules/async/lib/async.js:498:34)
    at processImmediate (timers.js:632:19)
```

**Comment by bmoers** [comment]
You might not have started the process with all required options once.
Check the payload under [point 5](https://github.com/bmoers/sn-cicd-example#installation-steps). If there are 'invalid' information in the db, just delete the files in /db/*.db, restart the server and run the job again.

**Comment by gitlabbin** [comment]
👍 , clean up the *.db help, test in V3 as well, close this issue, thanks for your explanation.
